### ISSUE TITLE
Module path should be "github.com/jpschroeder/pipe-to-me", not "pipe-to-me"

### ISSUE THREAD

**Issue by KateGo520** [jpschroeder/pipe-to-me#2]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, run `go get -u github.com/jpschroeder/pipe-to-me`:
```
go: downloading github.com/jpschroeder/pipe-to-me v0.0.0-20191212154931-8f031675506a
go: github.com/jpschroeder/pipe-to-me upgrade => v0.0.0-20191212154931-8f031675506a
go get: github.com/jpschroeder/pipe-to-me@v0.0.0-20191212154931-8f031675506a: parsing go.mod:
        module declares its path as: pipe-to-me
                but was required as: github.com/jpschroeder/pipe-to-me
```

###  Fix the module path:
Rename the module path to "github.com/jpschroeder/pipe-to-me".
https://github.com/jpschroeder/pipe-to-me/blob/master/go.mod#L1 
```
module github.com/jpschroeder/pipe-to-me
go 1.12 
```

**Comment by KateGo520** [comment]
@jpschroeder  Could you help me review this issue? Thx :p

**Comment by jpschroeder** [comment]
@KateGo520 Good catch.  I just pushed a fix for this.  Let me know if you have any other issues.

**Comment by KateGo520** [comment]
@jpschroeder Thank you for your reply. I see the commit. Thant helps a lot! Thank you for your contribution!
